### ISSUE TITLE
Proof of concept for the new architecture 

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-botComm#70]
# Goal
we need a way to make our data extraction and analysis scalable.

# needs
- Parallelly extract information from different sources and different guilds
- Parallelly analyze the stored raw information
- Have different analysis scripts working at the same time
- Have the ability to add more nodes of same analysis script for parallel analysis and load balancing
- Have the ability to run second, third, and Nth level analysis (analysis that uses the data of another analysis)

# Tasks

- [ ] [Create an instance of RabbitMQ in dev environment ](https://github.com/RnDAO/tc-operation/issues/18)
- [ ] Review and analyze the architecture 
- [ ] Research on best practices 
- [ ] Finalize the architecture
- [ ] Implement a basic version of the architecture as proof of concept

**Comment by mehrdadmms** [comment]
My suggestion for the architecture 
https://miro.com/app/board/uXjVPkg255E=/?share_link_id=678339601738
